Add more icons
bpmn-io/properties-panel-next pull request #56
Opened 2021-06-04 10:48 UTC by pinussilvestrus

Closes #13 

This PR
* adds all element icons
* removes the markers for now
* displays the header icon into a 32x32 viewbox

2021-06-04 12:19 UTC, pinussilvestrus commented
Don't know what's wrong with Codecov here...

2021-06-04 12:20 UTC, pinussilvestrus commented on src/bpmn-properties-panel/icons/index.js
> +import BusinessRuleTaskIcon from './bpmn-icon-business-rule-task.svg';
This file is really blown up by the number of icons. For now, I can't see real alternatives, because we have to very explicit.

2021-06-04 12:48 UTC, andreasgeier requested changes
A lot of icons do not show up in the header: transaction, all boundary events, all data-related elements, pool ...

2021-06-04 12:51 UTC, pinussilvestrus commented
I'll double-check. Probably some spelling mistakes with the types.

2021-06-04 13:20 UTC, pinussilvestrus commented
I updated the identifiers to show the correct icons.

2021-06-07 14:34 UTC, pinussilvestrus commented
> I updated the identifiers to show the correct icons. I also removed the legacy "default" icon, which was the old process icon. For now, nothing will be displayed if no icon was found.
> 
> The only missing icon seems to be for `Collaboration` though.

I added the missing icon, thanks to @andreasgeier (cf. https://github.com/camunda/camunda-modeler-design/issues/21)

2021-06-09 06:48 UTC, andreasgeier approved these changes
✅ &nbsp; All icons seem to be there now - good work!

2021-06-09 06:49 UTC, andreasgeier commented
I found a functional issue. When dropping the first pool to the canvas, the participant is selected but the properties panel shows the collaboration props. This happens only for the first pool, additional pools will show up in the panel correctly.

2021-06-09 06:51 UTC, pinussilvestrus commented
Let's [open an issue](https://github.com/bpmn-io/properties-panel-next/issues/new?assignees=&labels=bug&template=BUG_REPORT.md) for that 👍

2021-06-09 08:17 UTC, andreasgeier commented
Conditional flow icon is not showing up

2021-06-09 08:51 UTC, andreasgeier commented
default flow is missing as well

2021-06-09 09:45 UTC, pinussilvestrus commented
With https://github.com/bpmn-io/properties-panel-next/pull/56/commits/b204eb98b6be36f2603fb96030771c35d04e4e0f I added support for conditional + default flows. The icons were already present, just the detection failed.

![image](https://user-images.githubusercontent.com/9433996/121332206-ed717a80-c917-11eb-9916-a04d065b5033.png)

![image](https://user-images.githubusercontent.com/9433996/121332274-ff531d80-c917-11eb-99e5-3075d7739bc4.png)

----

Should be ready to review + merge now @barmac @MaxTru @andreasgeier. To not blow up this PR even further, let's consider open issues for further improvements (as missing icons).

2021-06-09 12:52 UTC, barmac commented
Is this expected that the icon changes its position for a super-long name of the element?

![image](https://user-images.githubusercontent.com/28307541/121357611-39311d80-c932-11eb-8c5a-d537c3319a02.png)

![image](https://user-images.githubusercontent.com/28307541/121357666-44844900-c932-11eb-97cd-aeaef88c5ad8.png)

2021-06-09 13:05 UTC, pinussilvestrus commented
Probably not. I fixed that to ensure the display box of the icon is stable.

![image](https://user-images.githubusercontent.com/9433996/121359759-19025e00-c934-11eb-9fce-53ac8b45c516.png)

![image](https://user-images.githubusercontent.com/9433996/121359781-1f90d580-c934-11eb-9b05-82136955382d.png)

2021-06-09 13:52 UTC, barmac approved these changes

2021-06-09 13:52 UTC, merged